<a href="https://colab.research.google.com/github/crasil/numpy-pandas-matplotlib/blob/main/02_conceptos_basicos_de_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Conceptos básicos de *Numpy*.

[*Numpy*](http://www.numpy.org/) es un paquete (o biblioteca) de Python, que provee un **objeto de arreglo multidimencional** (arrays o matrices), además de una variedad de **operaciones especializada en arreglos** (operaciones matemáticas, lógicas, algebra líneal, etc.).

>Documentación:https://docs.scipy.org/doc/numpy/.

## Instalación y carga del paquete ```numpy```.

- La instalación del paquete [*numpy*](https://pypi.org/project/numpy/) puede ser hecha mediante ```pip```. (En Linux: `pip install numpy`)
- Importar el paquete *Numpy* al proyecto:

In [2]:
import numpy as np
# Por convención se usa 'np' como alias de numpy

## Arreglos en *Numpy* `ndarray`.

El elemento primordial de *Numpy* es el objeto `ndarray`, Este encapsula un array multidimensional de tipos de datos homogéneos. Los arrays de *NumPy*:

- Son de tamaño fijo.
- Todos los elementos deben ser del mismo tipo.
- Son más eficientes que las secuencias estándar de Python.

In [10]:
type(np.array([]))

numpy.ndarray

### Crear arreglos *Numpy*
Existen muchas maneras de crear arreglos, lo mas usual es:

```
np.array(<estructura del arreglo>[, dtype=<tipo>])
```
* El parámetro `<estructura del arreglo>` es una **colección de datos indexables** (listas, tuplas, etc.) que pueden contener a su vez otras colecciones.

* El parámetro ```dtype``` indica el **tipo de dato de los elementos del arreglo**. En caso de que no se defina el tipo de dato, *NumPy*  tratará de deducirlo.

In [ ]:
# Crear un array Numpy
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
# Crear un array numpy a partir de tuplas
np.array((1,2,3))

array([1, 2, 3])

### Dimensión, forma y tamaño de los arreglos.

Los arreglos de *Numpy* son estructuras que a su vez pueden contener arreglos, a esto se denomina "dimensiones".

Todos los arreglos en una dimensión específica deben de contener el mismo número de elementos.

**El atributo `ndim`**

Indica el número de dimensiones del arreglo. *Retorna un número entero*.

**El atributo `shape`**

Describe el número de elementos que contiene cada dimensión. *Retorna una tupla*

```
(<n1>, <n2>, <n3> ... <nm>)
```

* Donde ```<n1>``` corresponde al número de elementos en la primera dimensión, así sucesivamente hasta la última dimensión ```<nm>```.

**El atributo `size`**

Contiene el número total de elementos del arreglo. *Retorna un número entero*

---
Ejemplos:

```
[1,2,3]         -> ndim:1, shape:(3,), size: 3

[[1,2,3],
 [4,5,6]]       -> ndim:2, shape:(2,3), size: 6

[[[1,2,3],
  [3,2,1]],
 [[5,6,7],
  [7,6,5]]]     -> ndim:3, shape:(2,2,3), size: 12

[[[1,2,3,4],
  [4,3,2,1]],
 [[5,6,7,8],
  [8,7,6,5]],
 [[7,8,9,0],
  [0,9,8,7]]]   -> ndim:3, shape:(3,2,4), size: 24
```

**Ejemplo:** Array de una dimensión

In [11]:
one_dim = np.array([1,2,3])
print(f"array: \t{one_dim}")
print(f"ndim:  \t{one_dim.ndim}")
print(f"shape: \t{one_dim.shape}")
print(f"size:  \t{one_dim.size}")

array: 	[1 2 3]
ndim:  	1
shape: 	(3,)
size:  	3


**Ejemplo:** Array de dos dimensiones

In [16]:
two_dim = np.array([[1,2,3],
                    [4,5,6]])
print(f"array: \n{two_dim}")
print(f"ndim:  \t{two_dim.ndim}")
print(f"shape: \t{two_dim.shape}")
print(f"size:  \t{two_dim.size}")


array: 
[[1 2 3]
 [4 5 6]]
ndim:  	2
shape: 	(2, 3)
size:  	6


**Ejemplo:** Array de tres dimensiones

In [17]:
three_dim = np.array([[[1,2,3],
                       [3,2,1]],
                      [[5,6,7],
                       [7,6,5]]])
print(f"array: \n{three_dim}")
print(f"ndim:  \t{three_dim.ndim}")
print(f"shape: \t{three_dim.shape}")
print(f"size:  \t{three_dim.size}")

array: 
[[[1 2 3]
  [3 2 1]]

 [[5 6 7]
  [7 6 5]]]
ndim:  	3
shape: 	(2, 2, 3)
size:  	12


## Tipos de datos de *Numpy*.

*Numpy* define tipos de datos que **extienden a los tipos de datos de Python**.

Estos tipos de datos pueden ser de **diversos tamaños**, dependiendo del número de bits asignado para almacenar dichos tipos.

Para mayor referencia consultar en: https://numpy.org/devdocs/user/basics.types.html

### El atributo ```dtype```.

Este atributo contiene el tipo de dato de un arreglo.

In [18]:
np.array([[1, 2, 3],
         [4, 5, 6]]).dtype

dtype('int64')

### Tipos enteros.

* Es posible definir enteros de distintos tamaños como ```np.int```, ```np.int8```, ```np.int16```, ```np.int32``` e ```np.int64```, los cuales pueden ser positivos, negativos o cero.

* Es posible definir **enteros sin signo**, tales como ```np.uint```,  ```np.uint8```, ```np.uint16```, ```np.uint32``` e ```np.uint64```.

> **Nota**: Si no se define el tipo de dato, Python utilizará un tipo de dato por defecto: ```int32``` o ```int64``` dependiendo del sistema en el que se ejecute esta notebook.

**Ejemplos:**

In [ ]:
# por defecto
np.array(((-1, 2), (3, 4))).dtype

dtype('int64')

In [ ]:
# Tipo uint8
np.array(((1, 2), (3, 4)), dtype = np.uint8).dtype

dtype('uint8')

In [ ]:
# uint64
np.array(((1, 2), (3, 4)), dtype = np.uint64).dtype

dtype('uint64')

### Tipos de punto flotante.

- Los tipos de punto flotante **siempre tendrán un signo** y son ```np.float``` ```np.float16```, ```np.float32```, ```np.float64```, ```np.float128```.

- Si el array contiene números enteros y flotantes, **Python convertirá** los enteros al tipo más genérico, en este caso **al tipo de punto flotante**.

> **Nota**: Si no se define el tipo de dato, Python utilizará: ```float32``` o ```float64``` dependiendo del sistema en el que se ejecute esta notebook.

**Ejemplos:**

In [ ]:
# por defecto
np.array([1., 2.6, 3.7]).dtype

dtype('float64')

In [ ]:
# Especificando el tipo
np.array([1., 2.6, 3.7], dtype=np.float128).dtype

dtype('float128')

In [ ]:
# mezclando tipos numericos
np.array([1, 2.0, 3, 4.0]).dtype
## [1. 2. 3. 4.]

dtype('float64')

### Tipos de bytes

~~Numpy puede gestionar arreglos de *bytes*.~~ (Deprecado) En su lugar usar `int8` o `uint8`

### Tipos complejos.

Los tipos de número complejo de *Numpy* son: ```np.complex_```, ```np.complex_```, ```np.complex64```, ```np.complex128```, ```np.complex256```.

**Ejemplo:**

In [ ]:
complejos = np.array([[25.6j, 11.24],
                     [-21.890-15702174.43j, 0]])
complejos

array([[  0.  +2.56000000e+01j,  11.24+0.00000000e+00j],
       [-21.89-1.57021744e+07j,   0.  +0.00000000e+00j]])

In [ ]:
complejos.dtype

dtype('complex128')

### Tipos booleanos.

El tipo ```np.bool_``` permite crear arreglos con valores booleanos.

>**Nota** recordar que Python identfica como ```True``` a cualquier valor distinto de ```0```.

**Ejemplo:**

In [ ]:
arr_booleans = np.array(((1,'Hola'), (False, 0)), dtype = np.bool_)
arr_booleans

array([[ True,  True],
       [False, False]])

In [ ]:
arr_booleans.dtype

dtype('bool')

### Tipos de texto.

Pueden ser de tipo ```np.string_```, ```np.unicode_``` o ```np.bytes_```. El tamaño de los elementos del arreglo corresponderá al elemento de texto más extenso.

A diferencia de Python 3, *Numpy* aún diferencia los tipos ```string``` y ```unicode```.

**Ejemplos:**

In [ ]:
np.array((['Hugo', 'Paco'],['Luis Ignacio', 'Donald']))

array([['Hugo', 'Paco'],
       ['Luis Ignacio', 'Donald']], dtype='<U12')

In [ ]:
np.array((['Hugo', 'Paco'],['Luis Ignacio', 'Donald']), dtype = np.unicode_)

array([['Hugo', 'Paco'],
       ['Luis Ignacio', 'Donald']], dtype='<U12')

In [ ]:
np.array((['Hugo', 'Paco'],['Luis Ignacio', 'Donald']), dtype = np.bytes_)

array([[b'Hugo', b'Paco'],
       [b'Luis Ignacio', b'Donald']], dtype='|S12')

In [ ]:
np.array((['Hugo', 'Paco'],['Luis Ignacio', 'Donald']), dtype = np.string_)

array([[b'Hugo', b'Paco'],
       [b'Luis Ignacio', b'Donald']], dtype='|S12')

Es posible definir el tamaño de los elementos por defecto utilizando la siguiente sintaxis al ingresar el argumento de ```dtype```, siendo ```S``` para *string* y ```U``` para *unicode*:

``` python
dtype="<S<tamaño>"
dtype="<U<tamaño>"
```

In [ ]:
np.array((['Hugo', 'Paco'],['Luis Ignacio', 'Donaldo']), dtype = "<U6")

array([['Hugo', 'Paco'],
       ['Luis I', 'Donald']], dtype='<U6')

### El tipo ```np.object```.

*NumPy* tiene un tipo de dato especial llamado `object` el cual permite almacenar datos de diferentes tipos en un array de *NumPy*

>**Nota** Se recomienda que **todos los elementos del array sean del mismo tipo** para que *NumPy* sea eficiente en términos de rendimiento y memoria.

In [ ]:
mix_arr = np.array(['d', 3 , (12, 6, True)], dtype=object)
# se debe indicar explicitamente el tipo `object`
mix_arr.dtype

dtype('O')

## Tipos de fecha.

### El tipo ```np.datetime64```.

Este tipo de datos permite crear arreglos compatibles con objetos de tipo ```datetime``` de Python.

Un valor de tipo ```np.datetime``` puede definirse también de la siguiente forma.
```
np.daytime64('<aaaa>-<mm>-<dd>T<hh>:<mm>:<seg>')
```

**Ejemplo:**

* Importar el tipo ```datetime``` del módulo ```datetime```.

In [ ]:
from datetime import datetime

* Crear un arreglo de forma ```(2, 2)``` que incluye 4 fechas.

In [ ]:
fechas = np.array(
    [[np.datetime64("2019-08-25T23:59:45.231"), np.datetime64("2020-07-23")],
     [np.datetime64(datetime(year=2018, month=12, day=22)), np.datetime64("2019-03-01T11:25")]])
fechas

array([['2019-08-25T23:59:45.231000', '2020-07-23T00:00:00.000000'],
       ['2018-12-22T00:00:00.000000', '2019-03-01T11:25:00.000000']],
      dtype='datetime64[us]')

### El tipo ```np.deltatime```.

El tipo ```np.deltatime``` es un valor numérico que corresponde a los segundos en un laspo de tiempo específico usando microsegundos como unidades.

**Ejemplo:**

* La siguiente celda utilizará la propiedad de "broadcasting" para calcular el tiempo transcurrido entre las fechas definidas en el arreglo ```fechas``` y el momento en le que se ejecute la celda.

In [ ]:
np.datetime64(datetime.now()) - fechas

array([[155519325091207, 126834510322207],
       [176860110322207, 170857410322207]], dtype='timedelta64[us]')

## Valores numéricos especiales.

*Numpy* es capaz de reconocer números indeterminados e infintios.

### El valor ```np.nan```.

*Numpy* utiliza ```np.nan``` cuando el valor **no se trata de un número o es una indeterminación**.

### El valor ```np.inf```.

El valor ```np.inf``` representa un **número muy grande** que no puede ser calculado (infinito). Dicho valor puede llevar signo.

**Ejemplos:**

* La siguiente celda creará un arreglo de números llamado ```numeros```.

In [ ]:
numeros = np.array(([1, 0],[-1, 1]))

In [ ]:
numeros

array([[ 1,  0],
       [-1,  1]])

* La siguiente celda dividirá entre ```0``` a cada elemento del arreglo ```numeros```. Debido a esto, es posible que el intérprete muestre algunas advertencias. Sin embargo, el resultado será un arreglo que contiene valores ```np.inf```, ```-np.inf``` y ```np.nan```.  

In [ ]:
numeros / 0

<ipython-input-119-4602ef416f76>:1: RuntimeWarning: divide by zero encountered in divide
  numeros / 0
<ipython-input-119-4602ef416f76>:1: RuntimeWarning: invalid value encountered in divide
  numeros / 0


array([[ inf,  nan],
       [-inf,  inf]])

* La siguiente celda definirá un arreglo con ```np.inf```, ```np.nan```

In [ ]:
np.array([[np.inf, np.nan],[1, 3]])

array([[inf, nan],
       [ 1.,  3.]])

* Aún cuando el resultado de la operación da por resultado números finitos, el valor del segundo elemento excede la capacidad del sistema.

In [ ]:
np.array((1, 2.5)) ** 2654

<ipython-input-121-461f6fb53824>:1: RuntimeWarning: overflow encountered in power
  np.array((1, 2.5)) ** 2654


array([ 1., inf])