<a href="https://colab.research.google.com/github/crasil/numpy-pandas-matplotlib/blob/main/03_gestion_de_arreglos_de_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Gestión de arreglos de Numpy

In [1]:
import numpy as np

## Creación de arreglos.

Además de ```np.array(<list|tupla>)``` es posible crear arreglos con ciertas características particulares.

### La función ```np.empty()```.

Crea un arreglo con valores arbitrarios (que no siempre se repite en cada ejecución).

```
np.empty(<forma> [, dtype=<tipo de dato>])
```

Donde:

* ```<forma>``` es una tupla que indica la forma del arreglo.
* ```<tipo de dato>``` es el tipo de dato que tendrá el arreglo.

El valor por defecto del parámetro ```dtype``` es ```np.float```.

**Ejemplos:**

In [2]:
# Crear un arreglo de forma (2,2)
np.empty((2, 2))

array([[4.92681618e-310, 0.00000000e+000],
       [4.03347227e-270, 4.15833851e-221]])

In [3]:
# Crear un array de tipo entero
np.empty((2, 3), dtype=np.int32)

array([[-680982936,      23217,  134349314],
       [ 134286337,  150929921,  305008647]], dtype=int32)

In [4]:
# Crear un array de tipo bool
np.empty((2, 2, 2), dtype=np.bool_)

array([[[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

In [5]:
# Crear un array de tipo texto
np.empty((2, 2, 4), dtype='>U10')

array([[['', '', '', ''],
        ['', '', '', '']],

       [['', '', '', ''],
        ['', '', '', '']]], dtype='>U10')

### La función ```np.ones()```.

Crea un array de valores `1`.


```
np.ones(<forma> [, dtype=<tipo de dato>])
```

Donde:

* ```<forma>``` es una tupla que indica la forma del arreglo.
* ```<tipo de dato>``` es el tipo de dato que tendrá el arreglo.

El tipo de dato **por defecto** es ```np.float```.

**Ejemplos:**

In [6]:
# Crear un array de 1s, de forma (2,3)
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
# Crar un array de tipo booleano
np.ones((2 ,3), dtype=np.bool_)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [8]:
# Crear un array de tipo string
np.ones((3, 3), dtype='|S1')

array([[b'1', b'1', b'1'],
       [b'1', b'1', b'1'],
       [b'1', b'1', b'1']], dtype='|S1')

### La función ```np.zeros()```.

Crea un array que contiene sólo valores `0`.

```
np.zeros(<forma> [, dtype=<tipo de dato>])
```

Donde:

* ```<forma>``` es una tupla que indica la forma del arreglo.
* ```<tipo de dato>``` es el tipo de dato que tendrá el arreglo.

El valor **por defecto** del parámetro ```dtype``` es ```np.float```.

**Ejemplos:**

In [9]:
# Crear un array de 0s
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
# Crear un array de booleanos
np.zeros((2, 3), dtype=np.bool_)

array([[False, False, False],
       [False, False, False]])

### La función ```np.arange()```.

La función ```np.arange()``` **generará un arreglo de una dimensión** definidos en un rango al estilo de ```range()```.

```
np.arange(<inicio>, <fin>, <incrementos>, dtype=<tipo de dato>)
```
Donde:

* ```<inicio>``` corresponde al número a partir del cual comenzará la secuencia. *Por defecto es `0`*
* ```<fin>``` corresponde al número (menos el último `<incremento>`) en el que terminará la secuencia (es excluyente).
* ```<incrementos>``` corresponde al número  unidades que se incrementarán sucesivamente. *Por defecto es `1`*
* ```<tipo de dato>``` es el tipo de dato del arreglo. Si no se especifica, se inferirá.

**Ejemplos:**

In [11]:
# Crear un array de enteros que va del 5 al 10 inclusive con increm. de 1.
np.arange(5, 11)

array([ 5,  6,  7,  8,  9, 10])

In [12]:
# Crear un array de valores flotantes que va del 5 al 10 exclusivo con incrementos de 0.5
np.arange(5, 10, 0.5)

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

### La función ```np.linspace()```.

Crea un array de una dimensión que contiene una secuencia lineal de números dentro de un rango dado.

```
np.linspace(<inicio, <fin>, num=<segmentos>, dtype=<tipo de dato>)
```

Donde:

* ```<inicio>``` corresponde al número a partir del cual comenzará la secuencia.
* ```<fin>``` corresponde al número en el que terminará la secuencia (inclusivo)
* ```<segmentos>``` correpsonde al número de segmentos, incluyendo el valor inicial y el final que se generarán, que contendrá el arreglo. *Valor por defecto es `50`*
* ```<tipo de dato>``` es el tipo de dato que tendrá el arreglo. *Por defecto es `np.float`*

**Ejemplos:**

In [13]:
# Crear un array compuesto por una secuencia lineal de 50 segmentos que van del 0 al 7.
np.linspace(0, 7)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ,
       2.14285714, 2.28571429, 2.42857143, 2.57142857, 2.71428571,
       2.85714286, 3.        , 3.14285714, 3.28571429, 3.42857143,
       3.57142857, 3.71428571, 3.85714286, 4.        , 4.14285714,
       4.28571429, 4.42857143, 4.57142857, 4.71428571, 4.85714286,
       5.        , 5.14285714, 5.28571429, 5.42857143, 5.57142857,
       5.71428571, 5.85714286, 6.        , 6.14285714, 6.28571429,
       6.42857143, 6.57142857, 6.71428571, 6.85714286, 7.        ])

In [14]:
# Crear un array compuesto por una secuencia lineal de 100 segmentos que van del 0 al 10.
np.linspace(0, 10, num=100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

### La función ```np.geomspace()```.

Esta función creará un arreglo de una dimensión que contiene una secuencia de números en una **escala logarítmica** dentro de un rango dado.

```
np.geomspace(<inicio, <fin>, num=<segmentos>, dtype=<tipo de dato>)
```

Donde:

* ```<inicio>``` corresponde al número a partir del cual comenzará la secuencia.
* ```<fin>``` corresponde al número en el que terminará la secuencia (inclusive)
* ```<segmentos>``` corresponde al número de segmentos, incluyendo el valor inicial y el final que se generarán, que contendrá el arreglo. *Por defecto es `50`*
* ```<tipo de dato>``` es el tipo de dato que tendrá el arreglo. *Por defecto es `np.float`*


**Ejemplo:**

* La siguiente celda creará un arreglo compuesto por una secuencia logarítmica de 100 segmentos que van del ```0``` al ```100```.

In [15]:
# Crear un arreglo compuesto por una secuencia logarítmica de 100 segmentos que van del 0 al 100.
np.geomspace(1, 100, num=100)

array([  1.        ,   1.04761575,   1.09749877,   1.149757  ,
         1.20450354,   1.26185688,   1.32194115,   1.38488637,
         1.45082878,   1.51991108,   1.59228279,   1.66810054,
         1.7475284 ,   1.83073828,   1.91791026,   2.009233  ,
         2.10490414,   2.20513074,   2.3101297 ,   2.42012826,
         2.53536449,   2.65608778,   2.7825594 ,   2.91505306,
         3.05385551,   3.19926714,   3.35160265,   3.51119173,
         3.67837977,   3.85352859,   4.03701726,   4.22924287,
         4.43062146,   4.64158883,   4.86260158,   5.09413801,
         5.33669923,   5.59081018,   5.85702082,   6.13590727,
         6.42807312,   6.73415066,   7.05480231,   7.39072203,
         7.74263683,   8.11130831,   8.49753436,   8.90215085,
         9.32603347,   9.77009957,  10.23531022,  10.72267222,
        11.23324033,  11.76811952,  12.32846739,  12.91549665,
        13.53047775,  14.17474163,  14.84968262,  15.55676144,
        16.29750835,  17.07352647,  17.88649529,  18.73

### La función ```np.logspace()```.

Esta función creará un arreglo de una dimensión que contiene una secuencia de números en una escala logarítmica que va de un rango dado entre $e^{incio}$ y un  $e^{fin}$ . El número de segmentos incluyendo el valor incial y el valor final es definido meduante el parámentro ```num```. El valor por defecto del parámetro ```num``` es de ```50```.

```
np.logspace(<inicio, <fin>, num=<segmentos>, dtype=<tipo de dato>)
```

Donde:

* ```<inicio>``` define el valor inicial de la secuencia. Este valor se calcula como $e^{<inicio>}$.
* ```<fin>``` define el valor final de la secuencia. Este valor se calcula como $e^{<fin>}$.
* ```<segmentos>``` corresponde al número de segmentos, incluyendo el valor inicial y el final que se generarán, que contendrá el arreglo. *Por defecto es `50`*.
* ```<tipo de dato>``` es el tipo de dato que tendrá el arreglo. *Por defecto es `np.float`*.

**Ejemplo:**

* La siguiente celda creará un arreglo compuesto por una secuencia logarítmica de 100 segmentos que van del $e^{12}$ a $e^{25}$.

In [16]:
np.logspace(12, 25, num=100)

array([1.00000000e+12, 1.35304777e+12, 1.83073828e+12, 2.47707636e+12,
       3.35160265e+12, 4.53487851e+12, 6.13590727e+12, 8.30217568e+12,
       1.12332403e+13, 1.51991108e+13, 2.05651231e+13, 2.78255940e+13,
       3.76493581e+13, 5.09413801e+13, 6.89261210e+13, 9.32603347e+13,
       1.26185688e+14, 1.70735265e+14, 2.31012970e+14, 3.12571585e+14,
       4.22924287e+14, 5.72236766e+14, 7.74263683e+14, 1.04761575e+15,
       1.41747416e+15, 1.91791026e+15, 2.59502421e+15, 3.51119173e+15,
       4.75081016e+15, 6.42807312e+15, 8.69749003e+15, 1.17681195e+16,
       1.59228279e+16, 2.15443469e+16, 2.91505306e+16, 3.94420606e+16,
       5.33669923e+16, 7.22080902e+16, 9.77009957e+16, 1.32194115e+17,
       1.78864953e+17, 2.42012826e+17, 3.27454916e+17, 4.43062146e+17,
       5.99484250e+17, 8.11130831e+17, 1.09749877e+18, 1.48496826e+18,
       2.00923300e+18, 2.71858824e+18, 3.67837977e+18, 4.97702356e+18,
       6.73415066e+18, 9.11162756e+18, 1.23284674e+19, 1.66810054e+19,
      

## Copiado de un arreglo.

La función ```np.copy()``` permite crear un nuevo arreglo a partir del que se ingresa como argumento.

```
np.copy(<arreglo>)
```

**Ejemplos:**

In [17]:
arreglo_original = np.array(([1, 2], [3, 4]))
print(arreglo_original)

arreglo_copia = np.copy(arreglo_original)
print(arreglo_copia)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [20]:
arreglo_original is arreglo_copia

False

## Escritura y lectura de arreglos en el sistema de archivos.

Numpy cuenta con varias funciones para almacenar y extraer arreglos a partir de archivos.

### Escritura de un arreglo  en un archivo de texto

La función ```np.savetxt()``` permite guardar un arreglo en un archivo  de texto

```
np.savetxt('<ruta>', <arreglo>, delimiter='<caracter delimitador>')
```

- Por defecto el  `<caracter delimitador>` es un espacio.

**Ejemplo:**

In [21]:
arreglo = np.array(([1, 2], [3, 4]), dtype=np.int8)
print(arreglo)

# Guardar el contenido en un archivo de texto
np.savetxt('arreglo.txt', arreglo)
print('>>>> Guardando el array en arreglo.txt')

# Visualizar el archivo creado con el comando cat
print('>>>> Visualizando el archivo')
%cat arreglo.txt

[[1 2]
 [3 4]]
>>>> Guardando el array en arreglo.txt
>>>> Visualizando el archivo
1.000000000000000000e+00 2.000000000000000000e+00
3.000000000000000000e+00 4.000000000000000000e+00


### Lectura de un arreglo a partir de un archivo de texto


La función ```np.loadtxt()``` permite leer un arreglo en un archivo de texto.

```
np.loadtxt('<ruta>', delimiter='<caracter delimitador>')
```

**Ejemplo:**

In [22]:
np.loadtxt("arreglo.txt")

array([[1., 2.],
       [3., 4.]])

### Escritura de arreglos en un archivo binario

#### Escritura de un arreglo

Esta función guardar un arreglo de *Numpy* en formato binario con la extensión ```.npy```.

```
np.save('<ruta>', <arreglo>)
```
- No es necesario poner la extensión del archivo, éste se añadirá automáticamente (ver ejemplo).

**Ejemplo:**

In [23]:
arreglo = np.array(([1, 2], [3, 4]))
print(arreglo)

# Guardando el arreglo en un archivo binario.
# Nota: La extension .npy se añadirá automáticamente
np.save('arreglo', arreglo)

# Visualizar el archivo creado
print('\n>>>> Visualizando el archivo')
%cat arreglo.npy

[[1 2]
 [3 4]]

>>>> Visualizando el archivo
�NUMPYv{'descr': '<i8', 'fortran_order': False, 'shape': (2, 2), }                                                          


#### Escritura de varios arreglos

Esta función es capaz de guardar más de un arreglo de *Numpy* en formato binario con la extensión La extensión ```.npz```.

```
np.savez('<ruta>', <arreglo 1>, <arreglo 2>,... <arreglo n>)
```
- No es necesario poner la extensión del archivo, éste se añadirá automáticamente (ver ejemplo).

**Ejemplo:**

In [24]:
arreglo_1 = np.array(([1, 2], [3, 4]))
arreglo_2 = np.array(([5, 6], [7, 8]))

# Guardar los arreglos en un archivo binario
# Nota: La extension .npz se añadirá automáticamente
np.savez('arreglos', arreglo_1, arreglo_2)

# Visualizar el archivo
%cat arreglos.npz

PK!�DK[��	arr_0.npy���NUMPYv{'descr': '<i8', 'fortran_order': False, 'shape': (2, 2), }                                                          
PK!�Y���	arr_1.npy���NUMPYv{'descr': '<i8', 'fortran_order': False, 'shape': (2, 2), }                                                          
PK!�DK[��	�arr_0.npyPK!�Y���	��arr_1.npyPKn�

### Lectura de arreglos a partir de un archivo binario

La función ```np.load()``` permite leer arreglos a partir de un archivo con extensión ```.npy``` o ```npz```.

```
np.load('<ruta>')
```

#### Lectura de archivos ```.npy```.

La función ```np.load()``` devuelve un arreglo de tipo ```np.ndarray```.

**Ejemplo:**

In [25]:
# Leer el archivo arreglo.npy y guardar en una variable
arreglo_leido = np.load('arreglo.npy')
print(arreglo_leido)

[[1 2]
 [3 4]]


#### Lectura de archivos ```.npz```.

En el caso de los archivos ```.npz```, la función ```np.load()``` regresará un objeto del tipo ```numpy.lib.npyio.NpzFile```.

Los arreglos pueden ser accedidos ya sea mediante iteraciones con ```for``` o mediante una clave.

```
<objeto-NpzFile>['arr_<n>']
```

- `<objeto-NpzFile>` es la variable que referencia al objeto NpzFile el cual contiene los arreglos.
- ```<n>``` es el índice del arreglo correspondiente a un número entero que va en orden ascendente a partir de ```0```.

**Ejemplo:**

In [26]:
# Leer el archivo binario arreglos.npz
arreglos_cargados = np.load('arreglos.npz')

# Visualizar el tipo del objeto
print(type(arreglos_cargados))

# Acceder al primer arreglo
print(arreglos_cargados['arr_0'])


<class 'numpy.lib.npyio.NpzFile'>
[[1 2]
 [3 4]]


In [27]:
# Acceder a todos los arreglos con un iterador for
for idx_arr in arreglos_cargados:
  print(idx_arr, arreglos_cargados[idx_arr])

arr_0 [[1 2]
 [3 4]]
arr_1 [[5 6]
 [7 8]]
