<a href="https://colab.research.google.com/github/carlosramos1/numpy-pandas-matplotlib/blob/main/03_lectura_escritura_archivos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Escritura y lectura de archivos.

*Numpy* cuenta con varias funciones para almacenar y extraer arreglos a partir de archivos.

In [ ]:
import numpy as np

## Escritura de un arreglo  en un archivo de texto

La función ```np.savetxt()``` permite guardar un arreglo en un archivo  de texto

```
np.savetxt('<ruta>', <arreglo>, delimiter='<caracter delimitador>')
```

- Por defecto el  `<caracter delimitador>` es un espacio.

**Ejemplo:**

In [ ]:
arreglo = np.array(([1, 2], [3, 4]), dtype=np.int8)
arreglo

array([[1, 2],
       [3, 4]], dtype=int8)

In [ ]:
# Guardar el contenido en un archivo de texto
np.savetxt('arreglo.txt', arreglo)

In [ ]:
# Visualizar el archivo creado con el comando cat
!cat arreglo.txt

1.000000000000000000e+00 2.000000000000000000e+00
3.000000000000000000e+00 4.000000000000000000e+00


## Lectura de un arreglo a partir de un archivo de texto


La función ```np.loadtxt()``` permite leer un arreglo desde un archivo de texto.

```
np.loadtxt('<ruta>', delimiter='<caracter delimitador>')
```

**Ejemplo:**

In [ ]:
np.loadtxt("arreglo.txt")

array([[1., 2.],
       [3., 4.]])

## Escritura de arreglos en un archivo binario

### Escritura de un arreglo

Esta función guardar un arreglo de *Numpy* en formato binario con la extensión ```.npy```.

```
np.save('<ruta>', <arreglo>)
```
- No es necesario poner la extensión del archivo, éste se añadirá automáticamente (ver ejemplo).

**Ejemplo:**

In [ ]:
arreglo = np.array(([1, 2], [3, 4]))
arreglo

array([[1, 2],
       [3, 4]])

In [ ]:
# Guardando el arreglo en un archivo binario.
np.save('arreglo', arreglo) #La extension .npy se añadirá automáticamente

In [ ]:
# Visualizar el archivo creado
!cat arreglo.npy

�NUMPYv{'descr': '<i8', 'fortran_order': False, 'shape': (2, 2), }                                                          


### Escritura de varios arreglos

La función `np.savez()` permite guardar más de un arreglo  en formato binario. La extensión del archivo es ```.npz```.

```
np.savez('<ruta>', <arreglo 1>, <arreglo 2>,... <arreglo n>)
```
- No es necesario poner la extensión del archivo, éste se añadirá automáticamente (ver ejemplo).

**Ejemplo:**

In [ ]:
arreglo_1 = np.array(([1, 2], [3, 4]))
arreglo_2 = np.array(([5, 6], [7, 8]))
arreglo_1, arreglo_2

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [ ]:
# Guardar los arreglos en un archivo binario
np.savez('arreglos', arreglo_1, arreglo_2) #La extension .npz se añadirá automáticamente

In [ ]:
# Visualizar el archivo
!cat arreglos.npz

PK-!�DK[��������	arr_0.npy���NUMPYv{'descr': '<i8', 'fortran_order': False, 'shape': (2, 2), }                                                          
PK-!�Y���������	arr_1.npy���NUMPYv{'descr': '<i8', 'fortran_order': False, 'shape': (2, 2), }                                                          
PK--!�DK[��	�arr_0.npyPK--!�Y���	��arr_1.npyPKn�

## Lectura de arreglos a partir de un archivo binario

La función ```np.load()``` permite leer arreglos desde archivos con extensión ```.npy``` o ```npz```.

```
np.load('<ruta>')
```

### Lectura de archivos ```.npy```.

La función ```np.load()``` devuelve un arreglo de tipo ```np.ndarray```.

**Ejemplo:**

In [ ]:
# Leer el archivo arreglo.npy y guardar en una variable
arreglo_leido = np.load('arreglo.npy')
print(arreglo_leido)

[[1 2]
 [3 4]]


### Lectura de archivos ```.npz```.

En el caso de los archivos ```.npz```, la función ```np.load()``` regresará un objeto del tipo ```numpy.lib.npyio.NpzFile```.

Los arreglos pueden ser accedidos ya sea mediante iteraciones con ```for``` o mediante un indice clave.

```
<objeto-NpzFile>['arr_<n>']
```

- `<objeto-NpzFile>` es la variable que referencia al objeto NpzFile el cual contiene los arreglos.
- ```arr_<n>``` Es un *string* que indica el índice del arreglo al que se quiere acceder, `<n>` es un número entero que va en orden ascendente a partir de ```0```.

**Ejemplo:**

In [ ]:
# Leer el archivo binario arreglos.npz
arreglos_cargados = np.load('arreglos.npz')

# Visualizar el tipo del objeto
print(type(arreglos_cargados))

<class 'numpy.lib.npyio.NpzFile'>


In [ ]:
# Acceder al primer arreglo
arreglos_cargados['arr_0']

array([[1, 2],
       [3, 4]])

In [ ]:
# Acceder a todos los arreglos con un iterador for
for idx_arr in arreglos_cargados:
  print(idx_a)
  print(idx_arr, arreglos_cargados[idx_arr])

arr_0 [[1 2]
 [3 4]]
arr_1 [[5 6]
 [7 8]]
