<a href="https://colab.research.google.com/github/carlosramos1/numpy-pandas-matplotlib/blob/main/04_indexacion_y_sustitucion_de_elementos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Indexación y modificación de arreglos

In [ ]:
import numpy as np

## Indexado de arreglos *NumPy*

Los `[ ]` permiten acceder a los elementos de un arreglo, de manera similar a las listas de *Python*.

Si el arreglo tiene múltiples dimensiones, los indices se separan con `,` para cada dimensión.


```
<arreglo>[<idx-dim1>, <idx-dim2>, ..., <idx-dimn>]
```

- `<idx-dimX>` es un número entero mayor o igual a `0`, donde `0` hace referencia al primer elemento de la dimensión en cuestión, así sucesivamente.


In [ ]:
a = np.array([4,5,6])

b = np.array([[1, 2, 3],
              [4, 5, 6]])

In [ ]:
# Acceder al segundo elemento del array `a`
print(a[1])

# Acceder al segundo elemento del array `b`
print(b[1])

5
[4 5 6]


In [ ]:
# Acceder al elemento que tiene el valor de 6 del array `b`
b[1,2]

6

### Rebanado de arreglos *NumPy*.

El rebanado permite **acceder a elementos contiguos** de un array, es similar al utilizado en *listas* y *tuplas* de *Python*

Si el arreglo tiene múltiples dimensiones, cada rango se separa con `,`.

```
<arreglo>[<rango-dim1>, <rango-dim2>, ... <rango-dimn>]
```

Donde:

* ```<rango-dimX>``` especifica un rango, y se denota: ```<m>:<n>:<i>```.
  - `<m>` es el inicio del rango
  - `<n>` es el fin del rango (*no inclusivo*)
  - `<i>` es el incremento, que *por defecto* es `1`.



**Ejemplo**

In [ ]:
#                Gr-1      Gr-2
x = np.array([[[1,3,5], [7, 9,11]],     # num impares
              [[2,4,6], [8,10,12]],     # num pares
              [[2,3,5], [7,11,13]]])    # num primos
x.shape

(3, 2, 3)

In [ ]:
# Obtener los números pares y primos
x[1:3]

array([[[ 2,  4,  6],
        [ 8, 10, 12]],

       [[ 2,  3,  5],
        [ 7, 11, 13]]])

In [ ]:
# Obtener los números impares y pares del Gr-2
x[0:2, 1]

array([[ 7,  9, 11],
       [ 8, 10, 12]])

In [ ]:
# Obtener los dos primeros números de cada Gr-2
x[:, 1, 0:2]

array([[ 7,  9],
       [ 8, 10],
       [ 7, 11]])

## Modificación de los elementos.

Para modificar un elemento se utiliza el índice y el operado de asignación ```=```.

In [ ]:
#                Gr-1      Gr-2
x = np.array([[[1,3,5], [7, 9,11]],     # num impares
              [[2,4,6], [8,10,12]],     # num pares
              [[2,3,5], [7,11,12]]])    # num primos
x.shape

(3, 2, 3)

In [ ]:
# Sustituir los num pares por [[4,4,4], [2,2,2]]
x[1] = [[4,4,4], [2,2,2]]
x

array([[[ 1,  3,  5],
        [11,  9,  7]],

       [[ 4,  4,  4],
        [ 2,  2,  2]],

       [[ 2,  3,  5],
        [ 7, 11, 13]]])

In [ ]:
# Sustituir el Gr-1 de num impares por [5,5,5]
x[0, 0] = [5,5,5]
x

array([[[ 5,  5,  5],
        [ 7,  9, 11]],

       [[ 1,  1,  1],
        [ 2,  2,  2]],

       [[ 2,  3,  5],
        [ 7, 11, 13]]])

In [ ]:
# Sustituir el 12 del Gr-2 de num primos por `13`
x[2, 1, 2] = 13
x

array([[[ 1,  3,  5],
        [ 7,  9, 11]],

       [[ 2,  4,  6],
        [ 8, 10, 12]],

       [[ 2,  3,  5],
        [ 7, 11, 13]]])

### Sustitución de elementos mediante rebanadas


In [ ]:
#                Gr-1      Gr-2
x = np.array([[[1,3,5], [11,9, 7]],     # num impares
              [[2,4,6], [8,10,12]],     # num pares
              [[2,3,5], [7,11,13]]])    # num primos
x.shape

(3, 2, 3)

In [ ]:
# Sustituir el 11 y 13 de los numeros primos por 17 y 19 respectivamente
x[2, 1, 1:3] = [17, 19]

x

array([[[ 1,  3,  5],
        [11,  9,  7]],

       [[ 2,  4,  6],
        [ 8, 10, 12]],

       [[ 2,  3,  5],
        [ 7, 17, 19]]])

## Indexación avanzada de arreglos.

Es posible acceder a varios elementos de una dimensión específica usando, como indices, un arreglo *NumPy* o una lista de  *Python*.


```
<arreglo>[<list-idx-1>, <list-idx-2>, ..., <list-idx-n>]
```

Donde:

* ```<list-idx-i>``` es un arreglo de *NumPy* o lista de *Python* de indices correspondiente a la i-esima dimensión.

### Obtener elementos de la 1ra dimensión

In [ ]:
#                Gr-1      Gr-2
x = np.array([[[1,3,5], [7, 9,11]],     # num impares
              [[2,4,6], [8,10,12]],     # num pares
              [[2,3,5], [7,11,13]]])    # num primos
x.shape

(3, 2, 3)

In [ ]:
# Obtener los num-primos y los num-impares en ese orden
indices = np.array([2, 0])

x[indices]

array([[[ 2,  3,  5],
        [ 7, 11, 13]],

       [[ 1,  3,  5],
        [ 7,  9, 11]]])

### Obtener elementos de varias dimensiones

Se debe pasar múltiples arrays separados por `,`

**NOTA:** Es necesario que los arreglos que se utilizarán como índices, sean de las mismas dimensiones y tamaños.

In [ ]:
#                Gr-1      Gr-2
x = np.array([[[1,3,5], [7, 9,11]],     # num impares
              [[2,4,6], [8,10,12]],     # num pares
              [[2,3,5], [7,11,13]]])    # num primos
x.shape

(3, 2, 3)

In [ ]:
# Obtener el Gr-2 de num-pares ([8,10,12]) y el Gr-1 de num-primos ([2,3,5])
indice_1ra_dim = [1, 2]   # num-pares y num-primos
indice_2da_dim = [1, 0]   # Gr-2 y Gr-1

x[indice_1ra_dim, indice_2da_dim]

array([[ 8, 10, 12],
       [ 7, 11, 13]])

### Obtener subconjuntos

Se puede pasar una lista de listas, donde cada sublista indica los indices del subconjunto

In [ ]:
#                Gr-1      Gr-2
x = np.array([[[1,3,5], [7, 9,11]],     # num impares
              [[2,4,6], [8,10,12]],     # num pares
              [[2,3,5], [7,11,13]]])    # num primos
x.shape

(3, 2, 3)

In [ ]:
# Obtener dos sub-conjuntos: un conj de pares e impares
#                            un conj de primos y pares
indices_conj_pares_impares = [1, 0]
indices_conj_primos_pares  = [2, 1]

indices_total = [indices_conj_pares_impares, indices_conj_primos_pares]

x[indices_total]

array([[[[ 2,  4,  6],
         [ 8, 10, 12]],

        [[ 1,  3,  5],
         [ 7,  9, 11]]],


       [[[ 2,  3,  5],
         [ 7, 11, 13]],

        [[ 2,  4,  6],
         [ 8, 10, 12]]]])