<a href="https://colab.research.google.com/github/carlosramos1/numpy-pandas-matplotlib/blob/main/05_broadcasting_y_operadores_aritmeticos_y_logicos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Broadcasting

Es un mecanismo que permite a los arrays expandir su dimensión y duplicar sus elementos a una forma específica.

Se aplica cuando hay alguna **operación entre arrays que tienen formas diferentes**, y además solo si los arrays son **compatibles entre si**.

Los usos más habituales del *broadcasting* son, para:

- Sustituir elementos de una región de un arreglo con otro arreglo más pequeño.
- Realizar operaciones aritméticas entre arreglos que tienen diferentes formas.

## Reglas de compatibilidad entre arrays.

Los array involucrados en el *broadcasting*, deben cumplir con la **regla de compatibilidad** descrita acontinuación.

Dado dos arrays que tienen un número de dimensiones y formas diferentes.

1. **Añadir dimensiones**: Al array que tiene menor número de dimensiones, añadir dimensiones extra hasta igualar al otro array.
2. **Duplicar elementos**: Los elementos se pueden duplicar si y solo si, el número de elementos en la i-esima dimensión es igual a 1. Los elementos se duplicarán hasta que coincida con el número de elementos del otro array. Este proceso se realiza en ambos arrays.
3. **Comprobar que ambos arrays son compatibles**: Luego del paso 1 y 2, verificar si ambos arrays tiene las mismas dimensiones y forma. Si es así entonces los arrays son compatibles, caso contrario no lo son.

### Ejemplos didáctico e ilustrativos

Ejemplo 1:

```
Consideremos el:
    array x -> [[[1,1,1], [1,1,1]],
                [[1,1,1], [1,1,1]],
                [[1,1,1], [1,1,1]]]
    x.shape -> (3,2,3)
    x.ndim  -> 3

    array y -> [[3], [6]]
    y.shape -> (2,1)
    y.ndim  -> 2

Verificar si son compatibles

1. Añadir dimensiones: al array `y`

    [[3], [6]]
    [[[3], [6]]]   y.shape -> (1,2,1), y.ndim -> 3

2. Duplicar elementos, a la i-esima dimensión que tenga 1 elemento

    y -> [[[3],[6]]]
    
    - dim-3 tiene un elemento, se duplica
      [[[3,3,3], [6,6,6]]]

    - dim-2 tiene dos elementos, no se duplica
      [[[3,3,3], [6,6,6]]]

    - dim-1 tiene un elemento, se duplica
      [[[3,3,3], [6,6,6]],
       [[3,3,3], [6,6,6]],
       [[3,3,3], [6,6,6]]]    y.shape -> (3,2,3), y.ndim -> 3

 3. Verificar el num. de dimensiones y la forma de los arrays.

      y.shape -> (3,2,3), y.ndim -> 3
      x.shape -> (3,2,3), x.ndim -> 3

      SI coinciden, por lo tanto, SON COMPATIBLES
```

Ejemplo 2:

```
Consideremos el:
    array x -> [[[1,1,1], [1,1,1]],
                [[1,1,1], [1,1,1]],
                [[1,1,1], [1,1,1]]]
    x.shape -> (3,2,3)
    x.ndim  -> 3

    array y -> [[3,2], [6,5]]
    y.shape -> (2,2)
    y.ndim  -> 2

Verificar si son compatibles

1. Añadir dimensiones: al array `y`

    [[3,2], [6,5]]
    [[[3,2], [6,5]]]   y.shape -> (1,2,2), y.ndim -> 3

2. Duplicar elementos, a la i-esima dimensión que tenga 1 elemento

    y -> [[[3,2], [6,5]]]
    
    - dim-3 tiene dos elemento, no se duplica
      [[[3,2], [6,5]]]

    - dim-2 tiene dos elementos, no se duplica
      [[[3,2], [6,5]]]

    - dim-1 tiene un elemento, se duplica
      [[[3,2], [6,5]],
       [[3,2], [6,5]],
       [[3,2], [6,5]]]   y.shape -> (3,2,2), y.ndim -> 3

 3. Verificar el num. de dimensiones y la forma de los arrays.

      x.shape -> (3,2,3), x.ndim -> 3
      y.shape -> (3,2,2), y.ndim -> 3

      NO coinciden, por lo tanto, NO SON COMPATIBLES
```


Ejemplo 3:

```
Consideremos el:
    array x -> [[1],[2],[3]]
    x.shape -> (3,1)
    x.ndim  -> 2

    array y -> [[5,6]]
    y.shape -> (1,2)
    y.ndim  -> 2

Verificar si son compatibles

1. Añadir dimensiones: no es necesario porque ambos tiene el mismo número de dimensiones.

    x.ndim -> 2 == y.ndim -> 2

2. Duplicar elementos, a la i-esima dimensión que tenga 1 elemento

    x -> [[1],[2],[3]]

    - dim-2 tiene un elemento, se duplica
      [[1,1],[2,2],[3,3]]

    - dim-1 tiene tres elementos, no se duplica
      [[1,1],[2,2],[3,3]]   x.shape -> (3,2), x.ndim -> 2
      
    y -> [[5,6]]

    - dim-2 tiene dos elementos, no se duplica
      [[5,6]]

    - dim-1 tiene un elemento, se duplica
      [[5,6],[5,6],[5,6]]   y.shape -> (3,2), y.ndim -> 2

 3. Verificar el num. de dimensiones y la forma de los arrays.

      x.shape -> (3,2), x.ndim -> 2
      y.shape -> (3,2), y.ndim -> 2

      SI coinciden, por lo tanto, SON COMPATIBLES
```

**Alternativamente**, de manera práctica se puede comprobar viendo directamente la forma de los arrays

```
Ejemplo 1-2

x.shape == (3,2,3)

y.shape == (3,)     # compatible
y.shape == (2,1)    # compatible
y.shape == (2,3)    # compatible
y.shape == (3,1,1)  # compatible

# results (3,2,3)

y.shape == (3,1)	# NOT compatible
y.shape == (2,2)	# NOT compatible
y.shape == (3,2)	# NOT compatible
```

```
Ejemplo 3
x.shape == (3,1)

y.shape == (1,2) or (2,)  # compatible
y.shape == (3,2)          # compatible

# results (3,2)

y.shape == (2,3)  # NOT compatible
y.shape == (3,)   # NOT compatible
```

```
Ejemplo 4
x.shape == (1, 2, 3, 5, 1, 11, 1, 17)
y.shape ==          (1, 7, 1,  1, 17)  # compatible

# results in shape (1, 2, 3, 5, 7, 11, 1, 17)
```

## Sustitución de elementos

*NumPy* permite sustituir elementos de una región específica repitiendo múltiples veces otro array más pequeño hasta ajustarse a las dimensiones del array afectado.

In [ ]:
M = np.array([[[1,2,3],
               [4,5,6]],

              [[9,8,7],
               [6,5,4]],

              [[10,20,30],
               [40,50,60]]])
M.shape

(3, 2, 3)

In [ ]:
# Sustituir el sub-array [6,5,4] por 0's
M[1,1] = [0]
# o M[1,1] = 0 es lo mismo
M

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 9,  8,  7],
        [ 0,  0,  0]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [ ]:
# Sustituir el subarray [[1,2,3], [4,5,6]] con el array [4,8,16]
M[0] = [4,8,16]
M

array([[[ 4,  8, 16],
        [ 4,  8, 16]],

       [[ 9,  8,  7],
        [ 0,  0,  0]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [ ]:
# Sustituir el subarray [[10,20,30], [40,50,60]] con el array [[5],[6]]
M[2] = [[5],[6]]
M

array([[[ 4,  8, 16],
        [ 4,  8, 16]],

       [[ 9,  8,  7],
        [ 0,  0,  0]],

       [[ 5,  5,  5],
        [ 6,  6,  6]]])

In [ ]:
# Sustituir el sub-array [[4, 8,16], [4,8,16]] con el array [4,8]
M[0] = [4,8]
M
#ValueError: could not broadcast input array from shape (2,) into shape (2,3)

ValueError: could not broadcast input array from shape (2,) into shape (2,3)

#### **Ejercicios**

* Dado el arreglo ```brigadas```.

||Brigada 1| Brigada 2|
|:--:|:---:|:---:|
|**Lunes**|Juan, Antonio, Ricardo|Alonso, Jorge, Salvador|
|**Martes**|David, Julian, Ricardo|Arturo, Ramiro, Esteban|
|**Miércoles**|Arturo, Ricardo, Lucio|Jorge, Marco, Juan|
|**Jueves**|Alonso, Julian, Salvador|Ricardo, Jorge, Esteban|
|**Viernes**|Lucio, Ramiro, Joaquín|Ricardo, Marco, Juan|

In [ ]:
brigadas = np.array( [[['Juan', 'Antonio', 'Ricardo'],
                       ['Alonso', 'Jorge', 'Salvador']],

                      [['David', 'Julian', 'Ricardo'],
                       ['Arturo', 'Ramiro', 'Esteban']],

                      [['Arturo', 'Ricardo', 'Lucio'],
                       ['Jorge', 'Marco', 'Juan']],

                      [['Alonso', 'Julian', 'Salvador'],
                       ['Ricardo', 'Jorge', 'Esteban']],

                      [['Lucio', 'Ramiro', 'Joaquín'],
                       ['Ricardo', 'Marco', 'Juan']]] )
brigadas.shape

(5, 2, 3)

- Reemplazar la brigada-2 del viernes por `Elton` *(ver la figura)*

||Brigada 1| Brigada 2|
|:--:|:---:|:---:|
|**Lunes**|Juan, Antonio, Ricardo|Alonso, Jorge, Salvador|
|**Martes**|David, Julian, Ricardo|Arturo, Ramiro, Esteban|
|**Miércoles**|Arturo, Ricardo, Lucio|Jorge, Marco, Juan|
|**Jueves**|Alonso, Julian, Salvador|Ricardo, Jorge, Esteban|
|**Viernes**|Lucio, Ramiro, Joaquín|```Elton, Elton, Elton```|

In [ ]:
# respuesta

array([[['Juan', 'Antonio', 'Ricardo'],
        ['Alonso', 'Jorge', 'Salvador']],

       [['David', 'Julian', 'Ricardo'],
        ['Arturo', 'Ramiro', 'Esteban']],

       [['Arturo', 'Ricardo', 'Lucio'],
        ['Jorge', 'Marco', 'Juan']],

       [['Alonso', 'Julian', 'Salvador'],
        ['Ricardo', 'Jorge', 'Esteban']],

       [['Lucio', 'Ramiro', 'Joaquín'],
        ['Elton', 'Elton', 'Elton']]], dtype='<U8')

* Reemplazar a las brigadas 1 y 2 del dia miércoles por: ```['Rocío', 'Martha', 'Angélica']```.

||Brigada 1| Brigada 2|
|:--:|:---:|:---:|
|**Lunes**|Juan, Antonio, Ricardo|Alonso, Jorge, Salvador|
|**Martes**|David, Julian, Ricardo|Arturo, Ramiro, Esteban|
|**Miércoles**|```Rocio, Martha, Angélica```|```Rocio, Martha, Angélica```|
|**Jueves**|Alonso, Julian, Salvador|Ricardo, Jorge, Esteban|
|**Viernes**|Lucio, Ramiro, Joaquín|Elton, Elton, Elton|

In [ ]:
# respuesta

array([[['Juan', 'Antonio', 'Ricardo'],
        ['Alonso', 'Jorge', 'Salvador']],

       [['David', 'Julian', 'Ricardo'],
        ['Arturo', 'Ramiro', 'Esteban']],

       [['Rocío', 'Martha', 'Angélica'],
        ['Rocío', 'Martha', 'Angélica']],

       [['Alonso', 'Julian', 'Salvador'],
        ['Ricardo', 'Jorge', 'Esteban']],

       [['Lucio', 'Ramiro', 'Joaquín'],
        ['Elton', 'Elton', 'Elton']]], dtype='<U8')

## Operaciones aritméticas

Los arreglos de *Numpy* son compatibles con los operadores artiméticos y lógicos de Python (suma, resta, multiplicacion, exponenciación, mayor, menor, etc.). El **requisito** principal es que ambos arrays seán **compatibles entre sí**.

**Cualquier operación** (aritmética o lógica) entre arrays **se realiza elemento a elemento**.

**Por ejemplo**: Sumar dos arrays de las mismas dimensiones.

\begin{equation}
\begin{pmatrix}
1 & 2\\
3 & 4\\
\end{pmatrix}
+
\begin{pmatrix}
1 & 1\\
1 & 1\\
\end{pmatrix}
=
\begin{pmatrix}
2 & 3\\
4 & 5\\
\end{pmatrix}
\end{equation}

Cuando los arrays tienen formas diferentes, se aplica el mecanismo de broadcasting.

**Por ejemplo**: Dado dos arrays de diferentes tamaño, realizar la multiplicación (elemento a elemento)

\begin{equation}
\begin{pmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
\end{pmatrix}
*
\begin{pmatrix}
2\\
1\\
\end{pmatrix}
\end{equation}

> **Ojo** NO es producto punto

Primero se aplica broadcasting al array `[[2],[1]]` y luego se realiza la operación.

\begin{equation}
\begin{pmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
\end{pmatrix}
*
\begin{pmatrix}
2 & 2 & 2\\
1 & 1 & 1\\
\end{pmatrix}
=
\begin{pmatrix}
2 & 4 & 6\\
4 & 5 & 6\\
\end{pmatrix}
\end{equation}

### 1. Operaciones entre un array y un elemento

La operación se realizará con cada uno de los elementos del array y el elemento suelto.

In [ ]:
M = np.array([[1,2,3],
              [4,5,6]])
M.shape

(2, 3)

In [ ]:
# Multiplicar por 5
M * 5

array([[ 5, 10, 15],
       [20, 25, 30]])

In [ ]:
# Aplicar un operador lógico
M > 4

array([[False, False, False],
       [False,  True,  True]])

### 2. Operaciones entre arrays

Ejemplo 1: Sumar dos arrays del mismo tamaño

In [ ]:
A = np.array([[ 1,  2,  3],
              [ 4,  0, -5]])
A.shape

(2, 3)

In [ ]:
B = np.ones((2,3), dtype=np.int32)
B.shape

(2, 3)

In [ ]:
R = A + B
R

array([[ 2,  3,  4],
       [ 5,  1, -4]])

In [ ]:
# Verificamos la forma del resultado
R.shape

(2, 3)

Ejemplo 2: Multiplicar dos arrays que tienen formas diferentes (1)

In [ ]:
M1 = np.array([[ 1,  2,  3],
               [ 4,  0, -5],
               [-2, -3, -4]])
M1.shape

(3, 3)

In [ ]:
M2 = np.array([2,3,5])
M2.shape

(3,)

In [ ]:
M1 * M2

array([[  2,   6,  15],
       [  8,   0, -25],
       [ -4,  -9, -20]])

Ejemplo 3: Multiplicar dos arrays que tienen distintas formas (2)


In [ ]:
# Crear el array `a`
a = np.array([[1],[2],[3]])
a.shape

(3, 1)

In [ ]:
# Crear el array `b`
b = np.array([[5,6]])
b.shape

(1, 2)

In [ ]:
# Multiplicar los arrays a * b
c = a * b
c

array([[ 5,  6],
       [10, 12],
       [15, 18]])

In [ ]:
# Verificamos la forma del array resultante
c.shape

(3, 2)

## Bibliografia

- https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting
- https://github.com/mCodingLLC/VideosSampleCode/blob/master/videos/032_numpy_broadcasting_explained/numpy_broadcasting.ipynb