<a href="https://colab.research.google.com/github/carlosramos1/numpy-pandas-matplotlib/blob/main/06_modificacion_de_arreglos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Recursos para arreglos de Numpy.

In [3]:
import numpy as np
np.__version__

'2.0.2'

## "Aplanado" de arreglos.

En algunos casos es conveniente obtener una lista o un arreglo de una dimensión que contenga a todos los elementos de un arreglo.

### El atributo ```flat```.

Este atributo es un objeto iterador ```np.flatiter``` capaz de regresar cada uno de los valores que contiene un arreglo.


https://numpy.org/devdocs/reference/generated/numpy.ndarray.flat.html

**Ejemplo:**

In [4]:
arreglo_1 = np.array([[1,  2,  3,  4],
                      [5,  6,  7,  8],
                      [9, 10, 11, 12]])

In [5]:
type(arreglo_1.flat)

numpy.flatiter

In [6]:
# Usar con ciclo for
for i in arreglo_1.flat:
  print(i, end=" ,")

1 ,2 ,3 ,4 ,5 ,6 ,7 ,8 ,9 ,10 ,11 ,12 ,

In [7]:
# Convertir a lista el iterador
list(arreglo_1.flat)

[np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9),
 np.int64(10),
 np.int64(11),
 np.int64(12)]

### El método ```flatten()```.

El método ```np.ndarray.flatten()``` **regresa un arreglo *NumPy* de una dimensión** que contiene una copia de cada uno de los elementos del arreglo original.

https://numpy.org/devdocs/reference/generated/numpy.ndarray.flatten.html

In [8]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [9]:
type(a.flatten())

numpy.ndarray

In [10]:
a.flatten()

array([1, 2, 3, 4])

### El método ```ravel()```.

El método ```np.ndarray.ravel()``` **regresa un array *NumPy* de una dimensión que contiene la <u>referencia</u> de cada uno de los elementos** del arreglo original. Por lo que, si se hace alguna modificación en el arreglo original se reflejará en el array aplanado.

https://numpy.org/devdocs/reference/generated/numpy.ndarray.ravel.html

In [11]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [12]:
a_ravel = a.ravel()
a_ravel

array([1, 2, 3, 4])

In [13]:
# Modificamos un elemento del array `a`
a[0,1] = 9
a

array([[1, 9],
       [3, 4]])

In [14]:
# Verificar si se ha modificado el array aplanado
a_ravel

array([1, 9, 3, 4])

### La función ```np.ravel()```.

Tiene la misma funcionalidad que el método `ndarray.ravel()`.

La función `np.ravel(<array-np>)` Retorna un arreglo de una dimensión que **contiene la <u>referencia</u>** de cada uno de los elementos del arreglo que se ingresa como argumento.

https://numpy.org/devdocs/reference/generated/numpy.ravel.html

In [15]:
a = np.array([[1,2], [3,4]])
a_ravel = np.ravel(a)
a_ravel

array([1, 2, 3, 4])

In [16]:
# Modificamos el elemento 0,0
a[0,0] = 9
# Verificamos que el array aplanado también cambió
a_ravel

array([9, 2, 3, 4])

## Modificación de la forma de los arreglos.

Existe dos maneras de **modificar la forma** de un arreglo:

- El método `np.ndarray.reshape()`
- La función `np.reshape()`

### El método ```reshape()```.

El método ```np.ndarray.reshape()``` retorna un arreglo compuesto por el mismo número de elementos que el arreglo original, pero con la forma que se ingrese como argumento.

Las nuevas dimensiones deben de coincidir con el numero total de elementos del arreglo de origen.

```
<arreglo>.reshape(<forma>)
```

* ```<forma>``` es una *tupla* que describe la forma del arreglo resultante.

https://numpy.org/devdocs/reference/generated/numpy.ndarray.reshape.html

In [17]:
a = np.array([[1,2], [3,4]])
a.shape

(2, 2)

In [18]:
# Modificar a la forma (4,1)
a.reshape((4,1))

array([[1],
       [2],
       [3],
       [4]])

In [19]:
# Ejemplo 2:
b = np.array([[1,2,3],[4,5,6],[6,7,8],[6,5,4]])
b.shape

(4, 3)

In [20]:
# Modificar a la forma (2,2,3)
b.reshape((2,2,3))

array([[[1, 2, 3],
        [4, 5, 6]],

       [[6, 7, 8],
        [6, 5, 4]]])

In [21]:
# Ejemplo 3:
a = np.array([[1,2], [3,4]])
a.shape

(2, 2)

In [22]:
# Modificar a la forma (3,1)
a.reshape((3,1))
# Error, porque el numero de elementos es menor al original

ValueError: cannot reshape array of size 4 into shape (3,1)

### La función ```np.reshape()```.

La función ```np.reshape()``` tiene la misma funcionalidad que el método `ndarray.reshape()`.

```
np.reshape(<arreglo>, <forma>)
```

* ```<arreglo>``` es un arreglo de *Numpy*.
* ```<forma>``` es un un objeto de tipo ```tuple``` que describe la forma del arreglo resultante.

https://numpy.org/devdocs/reference/generated/numpy.reshape.html


In [55]:
c = np.array([[1,2,3],[4,5,6],[6,7,8],[6,5,4,]])
np.reshape(c, (2,2,3))

array([[[1, 2, 3],
        [4, 5, 6]],

       [[6, 7, 8],
        [6, 5, 4]]])

## Modificación de la forma y tamaño de un arreglo.

Existen dos maneras de **modificar la forma y el tamaño**:

- El método ```np.ndarray.resize()```
- La función ```np.resize()```

### El método ```resize()```.

El método ```np.ndarray.resize()``` cambia la forma y el tamaño (si así fuese el caso) del arreglo.

- En caso de que las nuevas dimensiones sean menores al tamaño original, se recortarán los últimos de ellos.

- En caso de que las nuevas dimensiones sean mayores al tamaño original, los elementos faltantes serán sustituidos por una secuencia de ```0```.
```
<array-np>.resize(<forma>)
```

* ```<forma>``` es un objeto de tipo ```tuple``` que describe la nueva forma del arreglo resultante.

https://numpy.org/devdocs/reference/generated/numpy.ndarray.resize.html


In [56]:
d = np.array([[1, 2],
              [3, 4]])
print(f"Antes:\t {d.shape}")

d.resize((3,5))

print(f"Después: {d.shape}")

print(d)

Antes:	 (2, 2)
Después: (3, 5)
[[1 2 3 4 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


**Nota**: Si se intenta invocar al método `resize()` desde otro bloque de código, se genera un error `ValueError: cannot resize an array that references or is referenced
by another array in this way.`

In [57]:
# Redimensionar el array
d.resize((3, 3, 2))

### La función ```np.resize()```.

**Retorna un nuevo arreglo** a partir del arreglo que se ingrese como primer argumento, con la forma que se ingrese como segundo argumento.

```
np.resize(<array-np>, <forma>)
```

* ```<forma>``` es un objeto de tipo ```tuple``` que describe la nueva forma del arreglo resultante.

**Consideraciones**:

- En caso de que las nuevas dimensiones sean menores a tamaño original, **se recortarán los últimos** de ellos.

- En caso de que las nuevas dimensiones sean mayores al tamaño original, los elementos faltantes **serán sustituidos por una secuencia iterativa de los elementos contenidos en el arreglo original**.

https://numpy.org/devdocs/reference/generated/numpy.resize.html

In [58]:
d = np.array([[1, 2],
              [3, 4]])

d.shape

(2, 2)

In [59]:
# Redimensionar la forma y tamaño
d_resize = np.resize(d, (2, 4))
d_resize.shape


(2, 4)

In [60]:
# Verificamos sus elementos
d_resize

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [61]:
# El array original no es afectado
d

array([[1, 2],
       [3, 4]])

## Transformaciones de arreglos a partir de sus ejes.

### Ejes de los arreglos de *Numpy*.

En la terminología de *Numpy*, a cada dimensión de un arreglo le corresponde un número entero, a cada uno de estos enteros se le conoce como eje (axis).

A partir de lo anterior:
* Un arreglo unidimensional tiene al eje ```0```.
* Un arreglo bidimensional tiene a los ejes ```0``` y ```1```.
* Un arreglo tridimiensional tiene a los ejes ```0```, ```1``` y ```2```.
* Así sucesivamente.

### El método ```transpose()```.

Retorna un nuevo array con los ejes transpuestos (*reubicados*).

```
<array-np>.transpose(<ejes>)
```
- `<ejes>` Es una tupla para indicar cada eje que será transpuesto. *Por defecto* se invierte el orden. p.e. un array de forma `(2,4,1)` será traspuesto a `(1,4,2)`

> **Recordar** que cada eje se representa con un número: `0` para la primera dimensión, `1` para la segunda y así sucesivamente.


In [62]:
a = np.array([[[1,  2,  3,  4],
               [5,  6,  7,  8],
               [9, 10, 11, 12]]])
a.shape

(1, 3, 4)

In [63]:
# Transposición por defecto
a_t = a.transpose()
a_t.shape

(4, 3, 1)

In [64]:
# El array original no cambia
a.shape

(1, 3, 4)

In [65]:
# Ejemplo 2: Realizar una transposicion arbitraria
a_t2 = a.transpose( (1,0,2) )
a_t2.shape

(3, 1, 4)

In [66]:
a_t2

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

### El atributo `ndarray.T`

Es la misma funcionalidad del método `ndarray.transpose()` *sin argumentos*



```
<array-np>.T
```



In [67]:
# Ejemplo
b = np.array([[1,2],
              [3,4]])
b.T

array([[1, 3],
       [2, 4]])

### La función ```np.transpose()```

La función ```np.transpose()``` tiene la misma funcionalidad que el *método transpose*.

```
np.transpose(<array-np>, (<ejes>))
```

- `(<ejes>)` Es una tupla para indicar cada eje que será transpuesto. *Por defecto* se invierte el orden. p.e. un array de forma `(2,4,1)` será traspuesto a `(1,4,2)`

> **Recordar** que cada eje se representa con un número: `0` para la primera dimensión, `1` para la segunda y así sucesivamente.

In [68]:
c = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
c.shape

(3, 3)

In [69]:
# Trasposición por defecto
np.transpose(c)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [70]:
# Ejemplo 2: trasposición personalizada
d = np.arange(12).reshape((2,2,3))
d

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [71]:
print(np.transpose(d, (0,2,1)))
print(f"shape:\t{np.transpose(d, (0,2,1)).shape}")

[[[ 0  3]
  [ 1  4]
  [ 2  5]]

 [[ 6  9]
  [ 7 10]
  [ 8 11]]]
shape:	(2, 3, 2)


### La función ```np.rollaxis()```.

Retorna un nuevo arreglo que tiene **uno de sus ejes trasladado** a otra posición


```
np.rollaxis(<array-np>, <eje>, start=0)
```

- `<eje>` Se indica el eje que será reubicado
- `start` Indica la posición a la que se reubicará al *eje*. *Por defecto* es `0`


In [72]:
e = np.array([[[ 0,  1,  2], [ 3,  4,  5]],
              [[ 6,  7,  8], [ 9, 10, 11]]])
e.shape

(2, 2, 3)

In [73]:
# Mover el 3er eje a la 1ra posición
e_ra = np.rollaxis(e, 2)
# Por defecto lo mueve al principio
e_ra.shape

(3, 2, 2)

In [74]:
# Mover el 3er eje a la 2da posición
e_ra2 = np.rollaxis(e, 2, 1)
e_ra2.shape

(2, 3, 2)

## Modificación de dimensiones de arreglos.

### La función ```np.expand_dims()```.

Esta función añade un nuevo eje a un array *Numpy*

```
np.expand_dims(<array-np>, <eje>)
```

Donde:

* ```<eje>``` indica el índice de la dimensión (eje) donde se ubicará el nuevo eje.

In [75]:
a = np.array([1,2,3])
a.shape

(3,)

In [76]:
# Añadir un nuevo eje en la primera posición
a_exp = np.expand_dims(a, 0)
a_exp.shape

(1, 3)

In [77]:
a_exp

array([[1, 2, 3]])

In [78]:
# Añadir un nuevo eje en la segunda posicón
a_exp2 = np.expand_dims(a, 1)
a_exp2.shape

(3, 1)

In [79]:
a_exp2

array([[1],
       [2],
       [3]])

### La función ```np.squeeze()```.

Esta función eliminará una dimensión de un array *NumPy*.

```
np.squeeze(<array-np>, <eje>)
```

* ```<eje>``` indica el índice de la dimensión que será eliminada.

**Importante**: Solo se puede eliminar eje que tiene un elemento.


In [80]:
b = np.arange(9).reshape(3, 1, 3)
b

array([[[0, 1, 2]],

       [[3, 4, 5]],

       [[6, 7, 8]]])

In [81]:
# Eliminar el segundo eje
b_sq = np.squeeze(b, 1)
b_sq.shape

(3, 3)

In [82]:
b_sq

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [83]:
# Eliminar el primer eje lanzará error por que tiene 3 elementos
np.squeeze(b, 0)

ValueError: cannot select an axis to squeeze out which has size not equal to one

## Adición y eliminación de elementos a arreglos.

### La función ```np.concatenate()```.

Une varios arreglos en un eje determinado.

```
np.concatenate( (<a1>, <a2>, ...), <eje>)
```
- `(<a1>, <a2>, ...)` **una colección** (p.e. tupla) d**e arreglos**, los arreglos deben tener la misma forma, excepto (opcional) en el `<eje>` afectado.
- `<eje>` **indice de la dimensión** en donde se realizará la operación. *Por defecto es `0`*

In [118]:
a = np.array([[1, 2],
              [3, 4]])
print(f"forma del array 'a':\t{a.shape}")

b = np.array([[5,6]])
print(f"forma del array 'b':\t{b.shape}")

forma del array 'a':	(2, 2)
forma del array 'b':	(1, 2)


In [126]:
# Concatenar los arrays a y b
np.concatenate((a,b)) # equivalente a np.concatenate((a,b), 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [127]:
# Verificamos la forma resultante
np.concatenate((a,b)).shape

(3, 2)

In [121]:
# Ejemplo 2
c = np.array([[[1, 2],
               [3, 4]],

              [[1, 1],
               [1, 1]]])
print(f"forma del array 'c':\t{c.shape}")

d = np.array([[[5],
               [6]],

              [[7],
               [8]]])
print(f"forma del array 'd':\t{d.shape}")

forma del array 'c':	(2, 2, 2)
forma del array 'd':	(2, 2, 1)


In [122]:
# Unir los arrays c y d
np.concatenate((c,d), 2)

array([[[1, 2, 5],
        [3, 4, 6]],

       [[1, 1, 7],
        [1, 1, 8]]])

In [125]:
# Verificamos la forma resultante
np.concatenate((c,d), 2).shape

(2, 2, 3)

### La función ```np.append()```.

Retorna un nuevo array, al cual se le añadieron elementos al final de un array *Numpy*


```
np.append(<a-np-1>, <a-np-2>, axis=<eje>)
```

- `<a-np-1>` Array al que se le añadirá elementos
- `<a-np-2>` Array del cual se obtendrán los elementos que se añadirán al array `<a-np-1>`. Este array debe tener la misma forma que `<a-np-1>` excepto en la dimensión correspondiente a `<eje>`.
* ```<eje>``` El eje en el que se hará la inserción.

**Importante**: Si no especifica el valore del `<eje>`, el **resultado será un array plano**.

In [94]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

a.shape

(2, 2)

In [95]:
# Sin especificar el eje, resulta un array aplanado
np.append(a, b)

array([1, 2, 3, 4, 5, 6])

In [96]:
c = np.array([[7,8]])
print(f"shape de 'a':\t{a.shape}")
print(f"shape de 'c':\t{c.shape}")

shape de 'a':	(2, 2)
shape de 'c':	(1, 2)


In [97]:
# añadir 'c' a 'a'
np.append(a, c, axis=0)

array([[1, 2],
       [3, 4],
       [7, 8]])

In [98]:
# Si intentamos añadir 'c' en 'a' por el eje equivocado, dará ERROR porque
# no cumple con la restricción descrito en <a-np-2>
np.append(a, c, axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

### La función ```np.insert()```.

Inserta elementos a un arreglo en un eje indicado.

```
np.insert(<arr-np-1>, <posición>, <arr-np-2>, axis=<n>)
```

Donde:

* ```<arr-np-1>``` es un arreglo que se utilizará como referencia para hacer las inserciones.
* ```<posición>``` es un índice o un rango que indica dónde se hará la inserción.
* ```<arr-np-2>``` el array que será insertado. Should be shaped so that `arr-np-1[...,posición,...] = <arr-np-2` is legal..
* ```axis=<n>``` define el eje de referencia. En caso de no definirse, se regresará un arreglo aplanado.

In [107]:
a = np.array([[1,2],[3,4]])
b = np.array([7,8])

print(f"shape de 'a':\t{a.shape}")
print(f"shape de 'b':\t{b.shape}")

shape de 'a':	(2, 2)
shape de 'b':	(2,)


In [108]:
# Insertar 'b' en 'a' en la segunda posición correspondiente a la primera dimensión
np.insert(a, 1, b, axis=0)

array([[1, 2],
       [7, 8],
       [3, 4]])

In [109]:
# Si no se especifica el axis, se aplanará el array
np.insert(a, 1, b)

array([1, 7, 8, 2, 3, 4])

### La función ```np.delete()```

In [110]:
numerico = np.arange(20).reshape(4, 5)

In [111]:
numerico

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [112]:
np.delete(numerico, 1)

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [113]:
np.delete(numerico, 2, axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [114]:
np.delete(numerico, 2, axis=1)

array([[ 0,  1,  3,  4],
       [ 5,  6,  8,  9],
       [10, 11, 13, 14],
       [15, 16, 18, 19]])

In [115]:
np.delete(numerico, [0, 4, 2], axis=1)

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18]])

In [116]:
np.delete(numerico, np.s_[1:3], axis=0)

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])